### PR TITLE
Update and rename br to pt-br.php

### PR DESCRIPTION
**Pull request by PadowYT2**
There are sections that are not translated btw, [account](https://github.com/PadowHost/billing-docs/blob/patch-1/Languages/pt-br.php#L71-L74) & [domain](https://github.com/PadowHost/billing-docs/blob/patch-1/Languages/pt-br.php#L143-L151) sections

### CODE REVIEW

**Comment by VozDeOuro** [comment]
fixed :)

file need to be named as br.php 
because of the flag

**Comment by PadowYT2** [comment]
> fixed :)
> 
> file need to be named as br.php because of the flag

:+1:

**Comment by PadowYT2** [comment]
@VozDeOuro

**Comment by VozDeOuro** [comment]
> @VozDeOuro 

Yes ?

**Comment by PadowYT2** [comment]
Will you merge?

**Comment by VozDeOuro** [comment]
> Will you merge?

Done ;)

**Pull request merged**
